[Version]
Class=IEXPRESS
SEDVersion=3
[Options]
PackagePurpose=ExtractOnly
ShowInstallProgramWindow=0
HideExtractAnimation=0
UseLongFileName=1
InsideCompressed=0
CAB_FixedSize=0
CAB_ResvCodeSigning=0
RebootMode=I
InstallPrompt=%InstallPrompt%
DisplayLicense=%DisplayLicense%
FinishMessage=%FinishMessage%
TargetName=%TargetName%
FriendlyName=%FriendlyName%
AppLaunched=%AppLaunched%
PostInstallCmd=%PostInstallCmd%
AdminQuietInstCmd=%AdminQuietInstCmd%
UserQuietInstCmd=%UserQuietInstCmd%
SourceFiles=SourceFiles
[Strings]
InstallPrompt=¿Deseas instalar este programa?
DisplayLicense=C:\Users\mggma\Downloads\licencia_iexpress.txt
FinishMessage=Instalación completada. FlowLog se ha instalado correctamente para el uso exclusivo de COMUNICACIÓN 6 Estudio Creativo. Ya puede iniciar la aplicación. Se crearon 2 atajos que permitirán accder a la aplicación FlowLog y el otro al Monitor TV de Producción
TargetName=D:\Proyecto Comunicaciones SEIS App\FlowLog Instalador.EXE
FriendlyName=FlowLog - Comunicación 6 Estudio Creativo
AppLaunched=
PostInstallCmd=<None>
AdminQuietInstCmd=
UserQuietInstCmd=
FILE0="FlowLog Monitor.url"
FILE1="FlowLog_App.url"
[SourceFiles]
SourceFiles0=C:\Users\mggma\Desktop\TEMP\
[SourceFiles0]
%FILE0%=
%FILE1%=
